export default {
  "login": "oluwadamilola",
  "id": 16785941,
  "node_id": "MDQ6VXNlcjE2Nzg1OTQx",
  "avatar_url": "https://avatars0.githubusercontent.com/u/16785941?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/oluwadamilola",
  "html_url": "https://github.com/oluwadamilola",
  "followers_url": "https://api.github.com/users/oluwadamilola/followers",
  "following_url": "https://api.github.com/users/oluwadamilola/following{/other_user}",
  "gists_url": "https://api.github.com/users/oluwadamilola/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/oluwadamilola/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/oluwadamilola/subscriptions",
  "organizations_url": "https://api.github.com/users/oluwadamilola/orgs",
  "repos_url": "https://api.github.com/users/oluwadamilola/repos",
  "events_url": "https://api.github.com/users/oluwadamilola/events{/privacy}",
  "received_events_url": "https://api.github.com/users/oluwadamilola/received_events",
  "type": "User",
  "site_admin": false,
  "name": "oluwadamilola ",
  "company": null,
  "blog": "",
  "location": "lagos",
  "email": null,
  "hireable": true,
  "bio": "Software Engineer with B.sc in computer science.",
  "twitter_username": "Damilola_koju",
  "public_repos": 25,
  "public_gists": 0,
  "followers": 4,
  "following": 13,
  "created_at": "2016-01-19T21:15:47Z",
  "updated_at": "2020-08-19T17:09:06Z"
};
